message_store: &MESSAGE_STORE
    store_prefix: vumigo.
riak: &RIAK
  bucket_prefix: vumigo.

transport_names:
  - vumigo_router
exposed_names:
  - bulk_message_transport
  - survey_transport
  - multi_survey_transport
  - opt_out_transport

upstream_transport: vumigo_router
optout_transport: opt_out_transport

router_class: go.vumitools.api_worker.GoApplicationRouter
conversation_mappings:
    survey: survey_transport
    multi_survey: multi_survey_transport
    bulk_message: bulk_message_transport

# NOTE: the order is important
middleware:
  - account_middleware: go.vumitools.middleware.LookupAccountMiddleware
  - batch_middleware: go.vumitools.middleware.LookupBatchMiddleware
  - conversation_middleware: go.vumitools.middleware.LookupConversationMiddleware
  - optout_middleware: go.vumitools.middleware.OptOutMiddleware
  - storing_middleware: vumi.middleware.StoringMiddleware
  - logging_middleware: vumi.middleware.LoggingMiddleware
  - per_account_middleware: go.vumitools.middleware.PerAccountLogicMiddleware

tagging_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
account_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
batch_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
conversation_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
debit_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
storing_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
optout_middleware:
  keyword_separator: ' '
  case_sensitive: False
  optout_keywords:
    - stop
logging_middleware:
  log_level: debug
per_account_middleware:
  message_store: *MESSAGE_STORE
  riak: *RIAK
  accounts:
    # simon@praekeltfoundation.org on mbp
    4964b043754b4c9792e94b96a7ee8caf:
      # - yo: go.vumitools.middleware.YoPaymentHandler
      - sna: go.vumitools.middleware.SNAUSSDOptOutHandler
  yo:
    url: http://209.140.24.182/oprime/api/refund
    username: authzer
    password: rezthua
    amount: 1
    reason: 'Completing Afropinions Survey'
  sna:
    account_key: 4964b043754b4c9792e94b96a7ee8caf
    riak: *RIAK