worker_name: multi_survey_application
transport_name: multi_survey_transport
batch_size: 5

message_store:
  store_prefix: vumigo.
riak_manager:
  bucket_prefix: vumigo.
vxpolls:
  prefix: vumigo.
poll_name_list:
  - XXX
  - YYY
  - ZZZ
