transport_name: vxpolls_transport
dashboard_port: 8101
dashboard_path_prefix: 'dashboard/'
batch_size: 2
poll_id: 'poll-1'
questions:
  - copy: 'What is your favorite color? 1. Red 2. Yellow 3. Blue'
    label: favorite color
    valid_responses:
      - 1
      - 2
      - 3
  - copy: 'What shade of red? 1. Dark or 2. Light'
    label: what shade
    valid_responses:
      - 1
      - 2
    checks:
      equal:
          favorite color: 1
  - copy: 'What is your favorite fruit? 1. Apples 2. Oranges 3. Bananas'
    label: favorite fruit
    valid_responses:
      - 1
      - 2
      - 3
  - copy: 'What is your favorite editor? 1. Vim 2. Emacs 3. Other'
    valid_responses:
      - 1
      - 2
      - 3