transport_name: safaricom_sna_smpp_tx_transport

system_id: "system-id"
password: "password"
host: 10.226.7.111
port: 6692
system_type: smpp

interface_version: "34"
registered_delivery: "1"

smpp_bind_timeout: 10
smpp_enquire_link_interval: 10