transport_name: smpp_transport

system_id: "system_id"
password: "password"
host: some-host
port: 6128

interface_version: "34"
dest_addr_ton: 1
dest_addr_npi: 1
registered_delivery: 1

smpp_bind_timeout: 5
delivery_report_regex: "id:(?P<id>\\S{,65}) +sub:(?P<sub>.{1,3}) +dlvrd:(?P<dlvrd>.{1,3}) +submit date:(?P<submit_date>\\d*) +done date:(?P<done_date>\\d*) +stat:(?P<stat>[0-9,A-Z]{1,7}) +err:(?P<err>.{1,3}) +[Tt]ext:(?P<text>.{,20}).*"
