r_prefix: vumigo
pools:
  shortcode:
    tags: '[i for i in range(10001, 1001 + 1000)]'
    metadata:
      transport_type: sms
  longcode:
    tags: '["default%d" % i for i in range(10001, 10001 + 1000)]'
    metadata:
      transport_type: sms
  truteq:
    tags: '["*120*646*4*1*%d#" % i for i in range(0, 100)]'
    metadata:
      transport_type: sms
  integrat:
    tags: '["*120*99*987*10*%d#" % i for i in range(0, 100)]'
    metadata:
      transport_type: ussd
  xmpp:
    tags:
      - 's.dehaan@gmail.com'
    metadata:
      transport_type: xmpp
