r_prefix: vumigo
pools:
  shortcode:
    tags: '[i for i in range(1000, 1001 + 1000)]'
    metadata:
      display_name: "Short code"
      delivery_class: sms
      transport_type: sms
      server_initiated: true
  longcode:
    tags: '["default%d" % i for i in range(10001, 10001 + 1000)]'
    metadata:
      display_name: "Long code"
      delivery_class: sms
      transport_type: sms
      server_initiated: true
  truteq:
    tags: '["*120*646*4*1*%d#" % i for i in range(0, 100)]'
    metadata:
      display_name: "*120*646*4*1...#"
      delivery_class: ussd
      transport_type: ussd
      client_initiated: true
  integrat:
    tags: '["*120*99*987*10*%d#" % i for i in range(0, 100)]'
    metadata:
      display_name: "*120*99*987*10*...#"
      delivery_class: ussd
      transport_type: ussd
      client_initiated: true
  xmpp:
    tags:
      - 's.dehaan@gmail.com'
    metadata:
      display_name: "Google Talk"
      delivery_class: gtalk
      transport_type: xmpp
      server_initiated: true
      msg_options:
        transport_name: gtalk_vumigo
