message_store:
    store_prefix: vumigo.
riak:
    bucket_prefix: vumigo.
transport_names:
  - smpp_transport
  - gtalk_vumigo
  - truteq_transport
exposed_names:
  - vumigo_router
router_class: vumi.dispatchers.base.SimpleDispatchRouter
route_mappings:
  smpp_transport:
    - vumigo_router
  gtalk_vumigo:
    - vumigo_router
  truteq_transport:
    - vumigo_router
