transport_name: afropinions_smpp_transport

system_id: "system_id"
password: "password"
host: some-host
port: 1234

interface_version: "34"
dest_addr_ton: 1
dest_addr_npi: 1
registered_delivery: 1

smpp_bind_timeout: 5
delivery_report_regex: "id:(?P<id>\\S{,65}) +sub:(?P<sub>.{1,3}) +dlvrd:(?P<dlvrd>.{1,3}) +submit date:(?P<submit_date>\\d*) +done date:(?P<done_date>\\d*) +stat:(?P<stat>[0-9,A-Z]{1,7}) +err:(?P<err>.{1,3}) +[Tt]ext:(?P<text>.{,20}).*"

middleware:
  - logging_mw: vumi.middleware.LoggingMiddleware
  - storing_mw: vumi.middleware.StoringMiddleware
  - longcode_tagging_mw: vumi.middleware.TaggingMiddleware
  - shortcode_tagging_mw: vumi.middleware.TaggingMiddleware
  - normalize_msisdns_mw: go.vumitools.middleware.NormalizeMsisdnMiddleware

longcode_tagging_mw:
  incoming:
    addr_pattern: '^(\d{6,20})$'
    tagpool_template: 'afropinions_longcode'
    tagname_template: '\1'
  outgoing:
    tagname_pattern: '.*'
    msg_template: {}

shortcode_tagging_mw:
  incoming:
    addr_pattern: '^(\d{4,5})$'
    tagpool_template: 'afropinions_shortcode'
    tagname_template: '\1'
  outgoing:
    tagname_pattern: '.*'
    msg_template: {}

normalize_msisdns_mw:
  country_code: '256'

storing_mw:
  riak:
    bucket_prefix: vumigo.

